# BCH Coefficients

https://arxiv.org/pdf/2212.01290.pdf

In [100]:
import numpy as np
from math import factorial
import itertools

In [169]:
def generate_mn_indices(tuples, order, *args):
    if not tuples:
        print('args: ', args)
        print('pair: ', [pair for pair in args])
        if(sum(sum(pair) for pair in args) == order):
            yield args
    else:
        head = tuples[0]
        for (m, n) in head:
            print('head: ', head)
            if(sum(sum(pair) for pair in args) + m + n <= order):
                yield from generate_mn_indices(tuples[1:], order, *(args + ((m, n),)))

In [170]:
input_tuples = [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
g = generate_mn_indices([input_tuples.copy() for _ in range(2)], 3)
for gg in g:
    print(gg)

head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
args:  ((0, 1), (0, 1))
pair:  [(0, 1), (0, 1)]
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
args:  ((0, 1), (0, 2))
pair:  [(0, 1), (0, 2)]
((0, 1), (0, 2))
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
args:  ((0, 1), (1, 0))
pair:  [(0, 1), (1, 0)]
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
args:  ((0, 1), (1, 1))
pair:  [(0, 1), (1, 1)]
((0, 1), (1, 1))
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
args:  ((0, 1), (2, 0))
pair:  [(0, 1), (2, 0)]
((0, 1), (2, 0))
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
args:  ((0, 2), (0, 1))
pair:  [(0, 2), (0, 1)]
((0, 2), (0, 1))
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
args:  ((0, 2), (1, 0))
pair:  [(0, 2), (1, 0)]
((0, 2), (1, 0))
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
hea

In [171]:
def bchd(X, Y, order=2, persist=None):
    for o in range(1, order+1):
        print('Working with order', o, 'terms:')
        for k in range(1, o+1):
            print('k=', k, 'term contributions:')
            s = [(m, n) for m in range(o+1-k+1) for n in range(o+1-k+1) if m+n and m+n+k-1<=o]
            coefficient = (-1)**(k-1)/k
            print('s= ', s)
            
            g = generate_mn_indices([s.copy() for _ in range(k)], o)
            stri = ''
            for gg in g:
                for (x, y) in gg:
                    stri += (f'X^{x} * ' if x != 0 else '') + (f'Y^{y} * ' if y != 0 else '')
                print(gg)
                stri += ' + '
            print(str(coefficient) + stri)
            
            print(20 * '-')
            print(s)
            print('Coefficient: ', coefficient)
            print('\n')
        print('\n\n')
        print(30 * '=')
        print('\n\n')

In [114]:
X = np.array([[0, 1], [1,0]])
Y = np.array([[1, 0], [0, -1]])
print(X)
print(Y)

[[0 1]
 [1 0]]
[[ 1  0]
 [ 0 -1]]


In [172]:
bchd(X, Y, 3)

Working with order 1 terms:
k= 1 term contributions:
s=  [(0, 1), (1, 0)]
head:  [(0, 1), (1, 0)]
args:  ((0, 1),)
pair:  [(0, 1)]
((0, 1),)
head:  [(0, 1), (1, 0)]
args:  ((1, 0),)
pair:  [(1, 0)]
((1, 0),)
1.0Y^1 *  + X^1 *  + 
--------------------
[(0, 1), (1, 0)]
Coefficient:  1.0








Working with order 2 terms:
k= 1 term contributions:
s=  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
args:  ((0, 1),)
pair:  [(0, 1)]
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
args:  ((0, 2),)
pair:  [(0, 2)]
((0, 2),)
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
args:  ((1, 0),)
pair:  [(1, 0)]
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
args:  ((1, 1),)
pair:  [(1, 1)]
((1, 1),)
head:  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
args:  ((2, 0),)
pair:  [(2, 0)]
((2, 0),)
1.0Y^2 *  + X^1 * Y^1 *  + X^2 *  + 
--------------------
[(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
Coefficient:  1.0


k= 2 term contributions:
s=  [(0, 1), (1, 0)]
head:  [

In [684]:
import numpy as np
from functools import reduce
import itertools

def BCH_formula(inputs, order):
    n = len(inputs)

    def Lie_bracket(X, Y):
        return np.dot(X, Y) - np.dot(Y, X)

    def ad_operator(X, Y):
        return np.dot(X, Y) - np.dot(Y, X)

    def BCH_term(X, Y, k):
        if k == 0:
            return X
        result = np.zeros_like(X, dtype=float)
        term = Y.copy().astype(float)
        for i in range(k):
            result += term
            term = ad_operator(X, term)
            term = term.astype(float) / (i + 1)
        return result

    result = np.zeros_like(inputs[0], dtype=float)

    for k in range(1, order + 1):
        for indices in itertools.product(range(n), repeat=k):
            nested_ad_operators = reduce(ad_operator, (inputs[i] for i in indices[::-1]))
            result += ((-1)**(k-1) / np.math.factorial(k)) * BCH_term(inputs[indices[0]], nested_ad_operators, order - k)

    return result

# Example usage:
# Assume inputs is an array of 3 matrices and order is 2
#inputs = [np.array([[1, 2], [3, 4]]), np.array([[0, 1], [2, 3]]), np.array([[2, 0], [1, 2]])]
inputs = [np.array([[1, 0], [0, 1]]), np.array([[1, 0], [0, 1]]), np.array([[1, 0], [0, 1]])]
order = 2

result = BCH_formula(inputs, order)
print(result)

[[-1.5  0. ]
 [ 0.  -1.5]]


In [806]:
inputs = [
    np.array([[1,0], [0,1]]),
    np.array([[0,1], [1,0]]),
    np.array([[1,0], [0,-1]])
]

In [695]:
import numpy as np

def generate_mn_indices(tuples, order, *args):
    if not tuples:
        if sum(sum(pair) for pair in args) == order:
            yield args
    else:
        head = tuples[0]
        for (m, n) in head:
            if sum(sum(pair) for pair in args) + m + n <= order:
                yield from generate_mn_indices(tuples[1:], order, *(args + ((m, n),)))


def bchd(inputs, order=2, persist=None):
    terms = len(inputs)
    
    for o in range(1, order + 1):
        print('Working with order', o, 'terms:')
        for k in range(1, o + 1):
            print('k=', k, 'term contributions:')
            s = [
                (m, n) for m in range(o + 1 - k + 1) for n in range(o + 1 - k + 1) if m + n and m + n + k - 1 <= o
            ]
            coefficient = (-1) ** (k - 1) / k
            print('s= ', s)

            g = generate_mn_indices([s.copy() for _ in range(k)], o)
            stri = ''
            for gg in g:
                for i, (x, y) in enumerate(gg):
                    term = inputs[i]
                    stri += (f'Term_{i + 1}:\n{term[0, 0]}^{x} * {term[0, 1]}^{y} * ' 
                             f'{term[1, 0]}^{x} * {term[1, 1]}^{y}\n') if x != 0 or y != 0 else ''
                print(gg)
                stri += ' + '
            print(str(coefficient) + stri)

            print(20 * '-')
            print(s)
            print('Coefficient: ', coefficient)
            print('\n')
        print('\n\n')
        print(30 * '=')
        print('\n\n')


# Example usage with the provided input
inputs = [
    np.array([[1, 0, 3], [0, 1, 3], [8,3,1]]),
    np.array([[0, 1, 9], [1, 0, 5], [4,8,2]]),
    np.array([[1, 0, 4], [0, -1, 5], [5,7,2]])
]

bchd(inputs, order=3)

Working with order 1 terms:
k= 1 term contributions:
s=  [(0, 1), (1, 0)]
((0, 1),)
((1, 0),)
1.0Term_1:
1^0 * 0^1 * 0^0 * 1^1
 + Term_1:
1^1 * 0^0 * 0^1 * 1^0
 + 
--------------------
[(0, 1), (1, 0)]
Coefficient:  1.0








Working with order 2 terms:
k= 1 term contributions:
s=  [(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
((0, 2),)
((1, 1),)
((2, 0),)
1.0Term_1:
1^0 * 0^2 * 0^0 * 1^2
 + Term_1:
1^1 * 0^1 * 0^1 * 1^1
 + Term_1:
1^2 * 0^0 * 0^2 * 1^0
 + 
--------------------
[(0, 1), (0, 2), (1, 0), (1, 1), (2, 0)]
Coefficient:  1.0


k= 2 term contributions:
s=  [(0, 1), (1, 0)]
((0, 1), (0, 1))
((0, 1), (1, 0))
((1, 0), (0, 1))
((1, 0), (1, 0))
-0.5Term_1:
1^0 * 0^1 * 0^0 * 1^1
Term_2:
0^0 * 1^1 * 1^0 * 0^1
 + Term_1:
1^0 * 0^1 * 0^0 * 1^1
Term_2:
0^1 * 1^0 * 1^1 * 0^0
 + Term_1:
1^1 * 0^0 * 0^1 * 1^0
Term_2:
0^0 * 1^1 * 1^0 * 0^1
 + Term_1:
1^1 * 0^0 * 0^1 * 1^0
Term_2:
0^1 * 1^0 * 1^1 * 0^0
 + 
--------------------
[(0, 1), (1, 0)]
Coefficient:  -0.5








Working with order 3 te

In [710]:
def generate_indices(order, k, num_terms):
        #s = [(m, n) for m in range(o+1-k+1) for n in range(o+1-k+1) if m+n and m+n+k-1<=o]
        for _ in range(num_terms):
            s = []
            for o in range(1, order+1):
                s.append(o)
                for k in range(1, order+1):
                    s.append(k)
            print(s)

generate_indices(3,2,3)

[1, 1, 2, 3, 2, 1, 2, 3, 3, 1, 2, 3]
[1, 1, 2, 3, 2, 1, 2, 3, 3, 1, 2, 3]
[1, 1, 2, 3, 2, 1, 2, 3, 3, 1, 2, 3]


In [129]:
def generate_s(order, kth, num_terms, *args):
    print('generate_s.order:', order)
    print('generate_s.kth:', kth)
    print('generate_s.num_terms', num_terms)
    print('generate_s.args:', args)
    if args and len(args) == num_terms:
        if sum(args) != 0 and sum(args) <= order:
            yield args
    else:
        if sum(args) <= order:
            for o in range(order + 1 - kth + 1):
                yield from generate_s(order, kth, num_terms, *(args + (o,)))

In [107]:
# order = 2
# k = 1
# num_terms = 4
h = generate_s(3, 1, 2)
for hh in h:
    print(hh)

(0, 1)
(0, 2)
(0, 3)
(1, 0)
(1, 1)
(1, 2)
(2, 0)
(2, 1)
(3, 0)


In [215]:
inputs = [
    np.array([[1,0], [0,1]]),
    np.array([[0,1], [1,0]]),
]

In [328]:
inputs = [
    np.array([[1,0], [0,1]]),
    np.array([[0,1], [1,0]]),
    np.array([[1,0], [0,-1]]),
    np.array([[5,2], [6,9]])
]

In [321]:
def generate_s(order, kth, num_terms, *args):
    if args and len(args) == num_terms:
        if sum(args) != 0 and sum(args) <= order:
            yield args
    else:
        if sum(args) <= order:
            for o in range(order + 1 - kth + 1):
                yield from generate_s(order, kth, num_terms, *(args + (o,)))

In [324]:
def bchd_s(inputs, order=2):
    for o in range(1, order+1):
        print('Working with order', o, 'terms:')
        for k in range(1, o+1):
            print('k=', k, 'term contributions:')
            #s = [(m, n) for m in range(o+1-k+1) for n in range(o+1-k+1) if m+n and m+n+k-1<=o]
            sss = generate_s(o, k, len(inputs))
            s = []
            for ss in sss:
                s.append(ss)
            coefficient = (-1)**(k-1)/k
            g = generate_indices([s.copy() for _ in range(k)], o)
            output = ''
            for gg in g:
                denominator = ''
                for tups in gg:
                    for t in range(len(tups)):
                        if tups[t]:
                            output += chr(ord('A') + t) + '^' + str(tups[t])
                            denominator += str(tups[t]) + '!'
                #output += '+ '
                output += ' / (' + str(denominator) + ') + '
            
            print(output[:-2])
            
            print(20 * '-')
            print('Coefficient: ', coefficient)
            print('\n')
        print('\n\n')
        print(30 * '=')
        print('\n\n')

In [330]:
bchd_s(inputs, 4)

Working with order 1 terms:
k= 1 term contributions:
D^1 / (1!) + C^1 / (1!) + B^1 / (1!) + A^1 / (1!) 
--------------------
Coefficient:  1.0








Working with order 2 terms:
k= 1 term contributions:
D^2 / (2!) + C^1D^1 / (1!1!) + C^2 / (2!) + B^1D^1 / (1!1!) + B^1C^1 / (1!1!) + B^2 / (2!) + A^1D^1 / (1!1!) + A^1C^1 / (1!1!) + A^1B^1 / (1!1!) + A^2 / (2!) 
--------------------
Coefficient:  1.0


k= 2 term contributions:
D^1D^1 / (1!1!) + D^1C^1 / (1!1!) + D^1B^1 / (1!1!) + D^1A^1 / (1!1!) + C^1D^1 / (1!1!) + C^1C^1 / (1!1!) + C^1B^1 / (1!1!) + C^1A^1 / (1!1!) + B^1D^1 / (1!1!) + B^1C^1 / (1!1!) + B^1B^1 / (1!1!) + B^1A^1 / (1!1!) + A^1D^1 / (1!1!) + A^1C^1 / (1!1!) + A^1B^1 / (1!1!) + A^1A^1 / (1!1!) 
--------------------
Coefficient:  -0.5








Working with order 3 terms:
k= 1 term contributions:
D^3 / (3!) + C^1D^2 / (1!2!) + C^2D^1 / (2!1!) + C^3 / (3!) + B^1D^2 / (1!2!) + B^1C^1D^1 / (1!1!1!) + B^1C^2 / (1!2!) + B^2D^1 / (2!1!) + B^2C^1 / (2!1!) + B^3 / (3!) + A^1D^2 / (1!2

In [327]:
def generate_indices(tuples, order, *args):
    if not tuples:
        if(sum(sum(pair) for pair in args) == order):
            yield args
    else:
        head = tuples[0]
        for h in head:
            yield from generate_indices(tuples[1:], order, *(args + (h,)))      

In [262]:
x1 = np.array([[1,2], [0,3]])
x2 = np.array([[1,1], [0,1]])
np.matmul(x2, x1)

array([[1, 5],
       [0, 3]])